version: '3.8'

services:
  tts-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY}
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Możliwość dodania więcej usług w przyszłości, np.:
  # redis-cache:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

volumes:
  cache-data: